import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://acriotech.com';
  
  // List all routes in the application
  const routes = [
    '',
    '/about-us',
    '/abuse-policy',
    '/anti-spam-policy',
    '/company/careers',
    '/company/methodology',
    '/company/partners',
    '/contact-us',
    '/cookie-policy',
    '/gdpr-compliance',
    '/industries',
    '/industries/education',
    '/industries/financial-services',
    '/industries/government',
    '/industries/healthcare',
    '/industries/hospitality',
    '/industries/logistics',
    '/industries/manufacturing',
    '/industries/retail',
    '/industries/startups',
    '/insights',
    '/insights/blog',
    '/insights/case-studies',
    '/insights/news-press',
    '/insights/research-reports',
    '/insights/tech-trends',
    '/insights/webinars',
    '/insights/whitepapers',
    '/ipr-complaints',
    '/privacy-policy',
    '/refund-policy',
    '/security-compliance',
    '/services',
    '/services/ai-integration',
    '/services/api-development-integration',
    '/services/cloud-architecture',
    '/services/dedicated-development-teams',
    '/services/devops-ci-cd',
    '/services/maintenance-support',
    '/services/mobile-app-development',
    '/services/product-discovery',
    '/services/qa-testing',
    '/services/software-consulting',
    '/services/ui-ux-design',
    '/services/web-application-development',
    '/solutions',
    '/solutions/ai-intelligent-automation',
    '/solutions/business-process-automation',
    '/solutions/cloud-infrastructure',
    '/solutions/custom-software-development',
    '/solutions/data-analytics',
    '/solutions/digital-transformation',
    '/solutions/enterprise-software',
    '/solutions/legacy-system-modernization',
    '/terms-of-service',
    '/trademark-policy',
    '/work',
    '/work/featured-projects',
    '/work/open-source',
    '/work/our-clients',
    '/work/testimonials'
  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: route === '' ? 1 : 0.8,
  }));
}
